//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPTraining.DAL
{
    using ASPTraining.Models;
    using System;
    using System.Collections.Generic;

    public partial class Comment : IComment
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string User { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> Improvement_Id { get; set; }
    
        public virtual IImprovement Improvement { get; set; }
    }
}
