//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPTraining.DAL
{
    using ASPTraining.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Improvement : IImprovement
    {
        public Improvement()
        {
            this.Comments = new HashSet<IComment>();
        }

        public int ID
        {
            get { return Id; }
            set { Id = value; }
        }
        public int Id { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
    
        public virtual ICollection<IComment> Comments { get; set; }
        public virtual IStatus Status { get; set; }
    }
}
