//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPTraining.DAL
{
    using ASPTraining.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Status : IStatus, IComparable<IStatus>
    {
        public Status()
        {
            this.Improvements = new HashSet<Improvement>();
        }

        public int ID
        {
            get { return Id; }
            set { Id = value;  }
        }

        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Improvement> Improvements { get; set; }


        public int CompareTo(IStatus other)
        {
            return this.ID.CompareTo(other.ID);
        }
    }
}
