// <auto-generated />
namespace ASPTraining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201410101209483_addstatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
